name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
    your_npm_job_name:
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
             with:
              node-version: '14'
              check-latest: true
          - run: npm install
          - run: npm check-rules

